---

## ZSH install
oh_my_zsh_custom_theme_info: { url: "https://github.com/romkatv/powerlevel10k.git", dir_dest_name: powerlevel10k }
oh_my_zsh_custom_theme: powerlevel10k/powerlevel10k

oh_my_zsh_default_plugins:
  - ansible
  - alias-finder
  - encode64
  - git
  - colored-man-pages
  - ubuntu
  - aws
  - tmux
  - tmuxinator

oh_my_zsh_custom_plugins_info:
  - { url: "https://github.com/junegunn/fzf.git", dir_dest_name : fzf }
  - { url: "https://github.com/Treri/fzf-zsh.git", dir_dest_name: fzf-zsh }
  - { url: "https://github.com/zsh-users/zsh-autosuggestions.git", dir_dest_name: zsh-autosuggestions }
  - { url: "https://github.com/zdharma/fast-syntax-highlighting.git", dir_dest_name: fast-syntax-highlighting }
  - { url: "https://github.com/ptavares/zsh-tfenv.git", dir_dest_name: zsh-tfenv }
  - { url: "https://github.com/ptavares/zsh-tgenv.git", dir_dest_name: zsh-tgenv }
  - { url: "https://github.com/ptavares/zsh-pkenv.git", dir_dest_name: zsh-pkenv }
  - { url: "https://github.com/ptavares/zsh-direnv.git", dir_dest_name: zsh-direnv }
  - { url: "https://github.com/ptavares/zsh-kubectx.git", dir_dest_name: zsh-kubectx }
  - { url: "https://github.com/ptavares/zsh-sdkman.git", dir_dest_name: zsh-sdkman }

oh_my_zsh_custom_plugins:
  - fzf-zsh
  - zsh-autosuggestions
  - fast-syntax-highlighting
  - zsh-tfenv
  - zsh-tgenv
  - zsh-pkenv
  - zsh-direnv
  - zsh-kubectx
  - zsh-sdkman

oh_my_zsh_custom_plugins_command :
  - "$HOME/.oh-my-zsh/custom/plugins/fzf/install --all"
  - "fast-theme safari"

oh_my_zsh_custom_zsh_entries:
  - "export EDITOR=vim"
  - "# List only directories alias"
  - "alias lsd='ls -l | grep \"^d\"'"
  - "# List by size directories"
  - "alias ducks='du -cksh * | sort -hr | head -n 15'"
  - "# File Shortcuts"
  - "alias D='cd ~/Téléchargements'"
  - "alias p='cd ~/projects'"
  - "alias T='cd ~/tools'"
  - "# Program Shortcuts"
  - "alias gitStoreCredentials='git config credential.helper store'"
  - "alias vi='vim -O'"
  - "# AWS login"
  - "alias logIntoIpponAWS='aws-google-auth -p ippon-admin-aws -d 28800 -I C00lefphs -S 563310275444 -r arn:aws:iam::308846910468:role/role-admin-sre-ops-federated -u ptavares@ippon.fr'"
  - "# Tools Docker alias"
  - "# kubectl completion"
  - "if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi"
  - "#Touchscreen alias"
  - "alias touchscreenOn=\"/usr/bin/xinput enable 'ELAN Touchscreen'\""
  - "alias touchscreenOff=\"/usr/bin/xinput disable 'ELAN Touchscreen' \""