---

## ZSH install
oh_my_zsh_custom_theme_info: { url: "https://github.com/romkatv/powerlevel10k.git", dir_dest_name: powerlevel10k }
oh_my_zsh_custom_theme: powerlevel10k/powerlevel10k

oh_my_zsh_default_plugins:
  - ansible
  - alias-finder
  - encode64
  - git
  - colored-man-pages
  - ubuntu
  - aws
  - tmux
  - tmuxinator

oh_my_zsh_custom_plugins_info:
  - { url: "https://github.com/junegunn/fzf.git", dir_dest_name : fzf }
  - { url: "https://github.com/Treri/fzf-zsh.git", dir_dest_name: fzf-zsh }
  - { url: "https://github.com/zsh-users/zsh-autosuggestions.git", dir_dest_name: zsh-autosuggestions }
  - { url: "https://github.com/zdharma-continuum/fast-syntax-highlighting.git", dir_dest_name: fast-syntax-highlighting }
  - { url: "https://github.com/ptavares/zsh-custom-functions.git", dir_dest_name: zsh-custom-functions }
  - { url: "https://github.com/ptavares/zsh-tfswitch.git", dir_dest_name: zsh-tfswitch }
  - { url: "https://github.com/ptavares/zsh-tgswitch.git", dir_dest_name: zsh-tgswitch }
  - { url: "https://github.com/ptavares/zsh-pkenv.git", dir_dest_name: zsh-pkenv }
  - { url: "https://github.com/ptavares/zsh-direnv.git", dir_dest_name: zsh-direnv }
  - { url: "https://github.com/ptavares/zsh-kubectx.git", dir_dest_name: zsh-kubectx }
  - { url: "https://github.com/ptavares/zsh-sdkman.git", dir_dest_name: zsh-sdkman }
  - { url: "https://github.com/ptavares/zsh-exa.git", dir_dest_name: zsh-exa }
  - { url: "https://github.com/ptavares/zsh-z.git", dir_dest_name: zsh-z }
  - { url: "https://github.com/ptavares/zsh-terraform.git", dir_dest_name: zsh-terraform }
  - { url: "https://github.com/ptavares/zsh-auto-update-plugins.git", dir_dest_name: zsh-auto-update-plugins }


oh_my_zsh_custom_plugins:
  - fzf-zsh
  - zsh-autosuggestions
  - fast-syntax-highlighting
  - zsh-custom-functions
  - zsh-tfswitch
  - zsh-tgswitch
  - zsh-pkenv
  - zsh-direnv
  - zsh-kubectx
  - zsh-sdkman
  - zsh-exa
  - zsh-z
  - zsh-terraform
  - zsh-auto-update-plugins

oh_my_zsh_custom_plugins_command :
  - "$HOME/.oh-my-zsh/custom/plugins/fzf/install --all"
  - "fast-theme safari"

oh_my_zsh_custom_zsh_entries:
  - "export EDITOR=vim"
  - "# File Shortcuts"
  - "alias D='cd ~/Téléchargements'"
  - "alias P='cd ~/projects'"
  - "alias T='cd ~/tools'"
  - "# Program Shortcuts"
  - "alias vi='vim -O'"
  - "# AWS login"
  - "alias logIntoIpponAWS='aws-google-auth -p ippon-admin-aws -d 28800 -I C00lefphs -S 563310275444 -r arn:aws:iam::308846910468:role/role-admin-sre-ops-federated -u ptavares@ippon.fr'"
  - "# Tools Docker alias"
  - "# kubectl completion"
  - "if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi"

